Field.create!(ru: 'Sib-travel 24', en: 'Sib-travel 24')
Field.create!(ru: 'Заглавная', en: 'Welcome')
Field.create!(ru: 'О нас', en: 'About')
Field.create!(ru: 'Портфолио', en: 'Portfolio')
Field.create!(ru: 'Блог', en: 'Blog')
Field.create!(ru: 'Цены', en: 'Pricing')
Field.create!(ru: 'Команда', en: 'Team')
Field.create!(ru: 'Контакты', en: 'Contacts')
Field.create!(ru: 'некоторый текст', en: 'some text')
Field.create!(ru: 'Добро пожаловать в ', en: 'Welcome to ')
Field.create!(ru: 'Sib-travel', en: 'Sib-travel')
Field.create!(ru: 'некоторый текст', en: 'some text')
Field.create!(ru: 'Ссылка', en: 'Link')
Field.create!(ru: 'Вольфрам является творческим шаблон одна страница профессионально ручной для удовлетворения потребностей разработчиков. Вам не нужно иметь никаких специальных знаний для его настройки и регулировки для ваших нужд.', en: "Wolfram is a creative one page template professionally handcrafted to meet the needs of novice developers and experts alike. You don't need to have any special knowledge to set it up and adjust for your needs.")
Field.create!(ru: 'Что такого', en: "What's so")
Field.create!(ru: 'чудесного', en: "awesome")
Field.create!(ru: 'в этом?', en: "about it?")
Field.create!(ru: 'Расширенный настраиваемость и внимание к деталям поможет вам получить свой собственный сайт и работает в кратчайшие сроки.', en: "Advanced customizability and attention to details will help you get your own website up and running in no time.")
Field.create!(ru: 'Полностью отзывчивый', en: "Fully responsive")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Построен с LESS', en: "Built with LESS")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Функциональна форма контакта', en: "Functional contact form")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Два типа меню', en: "Two menu types")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Шесть опций шаблонов', en: "Six layout options")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: '5 цветовых схем', en: " 5 color schemes ")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Картина рисует', en: "A picture paints a")
Field.create!(ru: 'тысячу', en: "thousand")
Field.create!(ru: 'слов', en: "words")
Field.create!(ru: "Некоторые из работ мы можем гордиться. Не стесняйтесь обращаться к нам, если вам нравится, что вы видите.", en: "Some of the works we can be proud of. Feel free to contact us if you like what you see.")
Field.create!(ru: 'Все', en: "All")
Field.create!(ru: 'Категория 1', en: "Category 1")
Field.create!(ru: 'Категория 2', en: "Category 2")
Field.create!(ru: 'Категория 3', en: "Category 3")
Field.create!(ru: 'Категория 4', en: "Category 4")
Field.create!(ru: 'Ключевые', en: "Key")
Field.create!(ru: 'преимущества', en: "product")
Field.create!(ru: 'продукта', en: "features")
Field.create!(ru: 'Еще больше причин, чтобы купить этот шаблон. Больше прибыть с будущим обновлением.', en: "Even more reasons to purchase this template. More to come with a future update.")
Field.create!(ru: '01.', en: "01.")
Field.create!(ru: 'Пять цветовых решений', en: "Five color options")
Field.create!(ru: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.', en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.")
Field.create!(ru: '02.', en: "02.")
Field.create!(ru: 'Два типа меню', en: "Two menu types")
Field.create!(ru: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.', en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.")
Field.create!(ru: '03.', en: "03.")
Field.create!(ru: 'Полностью отзывчивый', en: "Fully Responsive")
Field.create!(ru: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.', en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.")
Field.create!(ru: '04.', en: "04.")
Field.create!(ru: 'Построен на LESS', en: "Built with LESS")
Field.create!(ru: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.', en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.")
Field.create!(ru: '05.', en: "05.")
Field.create!(ru: 'Функциональная форма контактов', en: "Functional contact form")
Field.create!(ru: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.', en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.")
Field.create!(ru: '06.', en: "06.")
Field.create!(ru: 'Бесплатные обновления в будущем', en: "Free future updates")
Field.create!(ru: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.', en: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. Morbi lacinia ut nibh eget euismod. Donec molestie odio sed leo interdum ultrices.")
Field.create!(ru: 'Около', en: "That's about")
Field.create!(ru: '6 чашек', en: "6 cups")
Field.create!(ru: 'кофе', en: "of coffee")
Field.create!(ru: 'Три ценовых категории для проектов любого размера. В случае неисполнения обязательств беспроблемный возврат гарантирован.', en: "Three pricing plans to fit a project of any size. Painless refund guaranteed.")
Field.create!(ru: 'Одностраничный сайт', en: "Single Application")
Field.create!(ru: '', en: "$")
Field.create!(ru: '600', en: "10")
Field.create!(ru: 'руб.', en: "/pc.")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Купить сейчас', en: "Purchase now")
Field.create!(ru: 'Многостраничный сайт', en: "Multiple Applications")
Field.create!(ru: '', en: "$")
Field.create!(ru: '3000', en: "50")
Field.create!(ru: 'руб. ', en: "/pc.")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at. ', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Купить сейчас', en: "Purchase now")
Field.create!(ru: 'Расширенный пакет', en: "Extended License")
Field.create!(ru: '', en: "$")
Field.create!(ru: '6000', en: "100")
Field.create!(ru: 'руб.', en: "/pc.")
Field.create!(ru: 'Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.', en: "Vivamus posuere ut est at gravida. Pellentesque non tempor mauris. Aliquam pharetra velit in vestibulum sollicitudin. Nulla mattis rhoncus tortor, sit amet egestas dolor pharetra at.")
Field.create!(ru: 'Купить сейчас', en: "Purchase now")
Field.create!(ru: 'Они делают', en: "They've")
Field.create!(ru: 'всё', en: "made")
Field.create!(ru: 'возможным', en: "this possible")
Field.create!(ru: 'Команда энтузиастов-трудоголиков, которая помогает этому проекту воплотиться в жизнь', en: "A team of hard-working enthusiastic people who helped this product come to life.")
Field.create!(ru: 'С легкостью', en: "Feel free to")
Field.create!(ru: 'обращайтесь к нам', en: "contact us")
Field.create!(ru: 'Не стесняйтесь, напишите нам пару строк. Поддержка 24/7 гарантирована.', en: "Do not hesitate to drop us a couple of lines. 24/7 support guaranteed.")
Field.create!(ru: 'Ваш адрес электронной почты', en: "Your email address")
Field.create!(ru: 'Ваше имя', en: "Your name")
Field.create!(ru: 'Ваше сообщение', en: "Your message")
Field.create!(ru: 'Послать сообщение', en: "Send message")
Field.create!(ru: '2016 © All Rights Reserved.', en: "2016 © All Rights Reserved.")
Field.create!(ru: 'http://yandex.ru/', en: "http://google.com/")
Field.create!(ru: 'http://yandex.ru/', en: "http://google.com/")
Field.create!(ru: 'http://yandex.ru/', en: "http://google.com/")



User.create!(email: 'qwe@rty.ui', password: 'qwertyui')
Background.create!(image: 'pic.jpg')
TeamMember.create!(name: "Judy Doe", info: "Lorem ipsum dolor sit amet, 
  consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. 
  Morbi lacinia ut nibh eget euismod.", photo: "/img/photo_2.jpg", 
  fb: "https://www.facebook.com/profile.php?id=100011258284339", status: 0, sort: 1)
TeamMember.create!(name: "Richard Roe", info: "Lorem ipsum dolor sit amet, 
  consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. 
  Morbi lacinia ut nibh eget euismod.", photo: "/img/photo_1.jpg", 
  vk: "https://vk.com/vikstruk", status: 0, sort: 2)
TeamMember.create!(name: "John Doe", info: "Lorem ipsum dolor sit amet, 
  consectetur adipiscing elit. Mauris at scelerisque diam, ut pellentesque leo. 
  Morbi lacinia ut nibh eget euismod.", photo: "/img/photo_3.jpg", 
  vk: "https://vk.com/vikstruk", status: 0, sort: 3)